language: python
python: "3.6"
cache: pip

matrix:
  include:
    # Run tests
    - addons:
        postgresql: "9.4"
      services:
        - postgresql
        - redis-server
      install:
        - "pip install -r requirements.txt"
        - "pip install -r requirements-dev.txt"
        - django-admin compilemessages
      script:
        - flake8
        - mypy .
        - py.test
        - createdb ndoh_hub
        - python manage.py makemigrations registrations changes --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
        - black --check .
        - isort -c -rc .

    # Create docker image on merge to develop
    - sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/ndoh-hub:develop
        - REGISTRY_USER=praekeltorgdeploy
        # REGISTRY_PASS
        - secure: "T5wWcq1DwbudN/agSQAEqJayoRkhyjP6hr6R8rUE/igdgYLY6D7qoLz1pAsM+O/kSBFHbPY6IdEKuiG+eQ/QxSfAYqoIvfSnVfEpaMcanB0mintqrlQJTO+OIHnagUNm1t/jqkfsQoLoPI4vPMm8n3rC/sIBlbf2l2AL9aZ2AY76SxAGcN26TIpa4D7lq6ouCx+eZvbt188nVTsCyk/kjOlIoToO1wmpTVx6WYBKSAwbA975bVYNotMBCkqD3dI7MH8KLvWQJPhwwkA0L5cGyg6EvEUrNZsev2RRjqcbv5xW4bgFrX4IoZL79wihi88vQumTp9R8toM6+ZpzqSwV1XpznbGxp//Um1CVy4nbuEXSrAhUoDfa8sRCU4dlTLYJiqHA6o4sPDrDpKy1irp9tmNoUZF0Zt++bWKDvTvbKH0mZnMFEEj9oJLqYR0dp+oXEpOn05sl1LOQUDXcfUJODT9aDIk+IQFyrBgnS/xNa6WNWiHq8bzHWhZ4o5WWjnVPye2WM4WuRJfZkjIGdGVZsv4NGcoFW0MzVRARytsj1fC8LoTpUWw+xvOvYh6jy0/EBzK2OFpFHTvwRMRucjwO1todVOkqaeJA4ifO0Bpt9vR1Hfu1hGvUFF1N1U7KALXNQ8NUpUcfGugOmYp3kDDMFErC595un9//CSskrUjiXPI="
      before_script:
        - docker pull "$IMAGE_NAME" || true
        - pip install -r seaworthy/requirements.txt
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
        - (cd seaworthy; py.test -v --hub-image "$IMAGE_NAME" test.py)

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
        on:
          branch: develop

    # Create docker images for tagged releases
    - sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/ndoh-hub
        - REGISTRY_USER=praekeltorgdeploy
        # REGISTRY_PASS
        - secure: "T5wWcq1DwbudN/agSQAEqJayoRkhyjP6hr6R8rUE/igdgYLY6D7qoLz1pAsM+O/kSBFHbPY6IdEKuiG+eQ/QxSfAYqoIvfSnVfEpaMcanB0mintqrlQJTO+OIHnagUNm1t/jqkfsQoLoPI4vPMm8n3rC/sIBlbf2l2AL9aZ2AY76SxAGcN26TIpa4D7lq6ouCx+eZvbt188nVTsCyk/kjOlIoToO1wmpTVx6WYBKSAwbA975bVYNotMBCkqD3dI7MH8KLvWQJPhwwkA0L5cGyg6EvEUrNZsev2RRjqcbv5xW4bgFrX4IoZL79wihi88vQumTp9R8toM6+ZpzqSwV1XpznbGxp//Um1CVy4nbuEXSrAhUoDfa8sRCU4dlTLYJiqHA6o4sPDrDpKy1irp9tmNoUZF0Zt++bWKDvTvbKH0mZnMFEEj9oJLqYR0dp+oXEpOn05sl1LOQUDXcfUJODT9aDIk+IQFyrBgnS/xNa6WNWiHq8bzHWhZ4o5WWjnVPye2WM4WuRJfZkjIGdGVZsv4NGcoFW0MzVRARytsj1fC8LoTpUWw+xvOvYh6jy0/EBzK2OFpFHTvwRMRucjwO1todVOkqaeJA4ifO0Bpt9vR1Hfu1hGvUFF1N1U7KALXNQ8NUpUcfGugOmYp3kDDMFErC595un9//CSskrUjiXPI="
      before_script:
        - docker pull "$IMAGE_NAME" || true
        - pip install -r seaworthy/requirements.txt
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
        - (cd seaworthy; py.test -v --hub-image "$IMAGE_NAME" test.py)

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git tag -l --points-at HEAD)" --version-semver --version-latest "$IMAGE_NAME"
        on:
          tags: true
