version: "3"

services:
  db:
    image: postgres:alpine
  rabbitmq:
    image: rabbitmq:alpine
  web:
    build: .
    image: ndoh-hub
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      - HUB_DATABASE=postgres://postgres:@db/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq//
  celery:
    image: ndoh-hub
    depends_on:
      - db
      - rabbitmq
    environment:
      - HUB_DATABASE=postgres://postgres:@db/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq//
    command: >
      celery worker --concurrency=1 --app=ndoh_hub --loglevel info
      -Q ndoh_hub,priority,mediumpriority,metrics,celery
